### ISSUE TITLE
Consider switching to gengo

### ISSUE THREAD

**Issue by lavalamp** [src-d/go2idl#2]
...not sure what this repo is but gengo is newer and is where development will continue: http://github.com/kubernetes/gengo

**Comment by Serabe** [comment]
Hello, @lavalamp:

We were researching the options to get proto3 message definitions based on Go structs when we found `go2idl` inside k8s. I filter-branched k8s to ease our first tests and remove hardcoded configurations.

Later, when looking for issues and PRs about upgrading go2idl to proto3, I got into gengo and it's what we are looking into now to generate the proto files.

Is there any ongoing or planned effort on supporting proto3 sytax in go2idl? Is there any interest on extracting go2idl to its own repo so more people can use it instead of having it as subdirectories of other tools?

Thank you!

**Comment by lavalamp** [comment]
Gengo *is* go2idl, mostly exactly what you did here, just renamed. It's in
use by Kubernetes so it should stay working :)

I don't recall where we are on proto2 vs 3, please feel free to file an
issue there.

Also I think at some point we will probably separate the utilities (proto
output etc) from the gengo library.

**Comment by Serabe** [comment]
Ok. Removing the repo. Thank you.

**Comment by Serabe** [comment]
Forked gengo in [src-d/gengo](https://github.com/src-d/gengo).
